---
title: "Syllabus"
page-layout: full
#format:
#  pdf: default
---
  
## Course description

This course explores the industrial organization of healthcare markets in the U.S., sometimes referred to as supply-side health economics or the economics of healthcare (to differentiate from the economics of health). We will focus on the following areas: health insurance,  physician agency, healthcare pricing and competition, information disclosure, physician learning, and healthcare waste. As we cover some of the key papers in these areas, we will discuss and employ tools from the fields of empirical IO and causal inference. These methods will be discuseed as needed throughout the course, but students are expected to have a working knowledge of these methods prior to the start of the course. 

Supply-side health economics is a rapidly growing field with many new developments, particularly in the areas of bargaining in two-sided markets, information disclosure, and physician learning. Some of these recent developments use tools from network analysis and machine learning, which we unfortunately do not have time to cover in this course. I've also chosen specific topics that overlap most with my own research --- the upside here is that I can speak somewhat confidently about the literature and empirical studies in this area, but the downside is that some very interesting areas of health economics are not studied. For example, we will largely ignore issues of the prescription drug market, medical devices, and physician labor supply. My hope is that the content that we do cover will provide a springboard for those interested in these other important areas.

## Learning outcomes

I have four central goals for this course:

1. Synthesize the current literature in each of the main areas of health economics covered in this class
2. Apply standard causal inference techniques in the area of healthcare
3. Organize real-world data with current workflow and versioning tools
4. Develop your own preliminary research in some area of healthcare economics

Our class times and your presentations are designed to help achieve the first goal; the second and third goals are part of our empirical exercise project; and the final goal is achieved through the research proposals and research plan. The assignments are described in more detail on the [class assignments page](https://econ771s24.classes.ianmccarthyecon.com/assignments).

## Text, Software, and Class Materials

1. **Readings:** As an elective PhD course, we will rely on academic papers from the reading list in each module. I expect everyone to read the papers in advance and come to class with questions on the study's contribution, empirical techniques, identification strategies, and datasets used. My goal with each paper is to discuss the analysis in as much detail as possible within our time constraints. As such, we'll focus on relatively fewer papers in class. I've provided a more comprehensive reading list in each module for those interested in additional readings in a specific area.

2. **Software:** For anything data related, I'll use `R`, but you are free to use whatever software you're most comfortable with in your empirical work. I encourage you to use `R`, `Stata`, or `Python` simply because these are the most common programs used in practice right now. You'll also need to have a basic working knowledge of Git and GitHub. If you're new to these tools, take a look at [Grant McDermott's](https://grantmcdermott.com/) notes on [Data Science for Economists](https://github.com/uo-ec607/lectures) as well as [Jenny Bryan's](https://jennybryan.org/) online reference book, [Happy Git and GitHub with R](https://happygitwithr.com/).

3. **Logistics:** For day-to-day communication, grades, and other private information (such as Zoom meeting links if needed), I'll use **Canvas**. I'll post all other materials to our class website. Please be sure to set up you **Canvas** alerts so that you receive class announcements in a timely manner.

4. **Slides and Notes:** Any presentations will be made available on our class website prior to any given class.

## Course policies

Various policies for this course are described below. Basically, let's all work to be good citizens and take seriously our various roles as a student, teacher, friend, colleague, human, etc.

### Academic integrity

The Emory University Honor Code is taken seriously and governs all work in this course. Details about the Honor Code are available in the Laney Graduate School Handbook and available online [here](https://www.gs.emory.edu/academics/policies-progress/conduct.html). By taking this course, you affirm that it is a violation of the code to plagiarize, to deviate from the instructions about collaboration on work that is submitted for grades, to give false information to a faculty member, and to undertake any other form of academic misconduct. You also affirm that if you witness others violating the code you have a duty to report them to the honor council.

### Accessibility services

If you anticipate issues related to the format or requirements of this course, please meet with me. I would like us to discuss ways to ensure your full participation in the course. If you determine that accommodations are necessary, you may register with Accessibility Services at (404)727-9877 or via e-mail at accessibility@emory.edu. To register with OAS, students must self identify and initiate contact with the OAS office.


### Communication

I will post regular announcements to the class on **Canvas**, so please set up your notifications on **Canvas** accordingly. I will also use **Canvas** to post all grades and any other information that needs to stay in the class (like our **Zoom** meeting link for virtual meetings, if needed). All other course materials will be available on our class website, [econ771s24.classes.ianmccarthyecon.com/](https://econ771s24.classes.ianmccarthyecon.com).

Please feel free to reach out to me for any reason. I generally respond to all e-mails within 24 hours.


### Office Hours

My designated office hours are 1:30-2:15pm on Monday and Wednesday in R432 of the R. Randall Rollins building. I'm happy to meet outside of normal office hours as well. Please feel free to schedule another time to meet by following the link to select a time that works for you, [https://mccarthy-meetings.youcanbook.me](https://mccarthy-meetings.youcanbook.me). Unless otherwise noted, all meetings will be held in my office. If you need to meet virtually, please let me know and I'll send you a **Zoom** link.


### Attendance

While there is no official "attendance" credit, everyone is expected to attend all class sessions. Given our small class, it is very important that we are all present and engaged.


## Assignments and Grading

There are four main assignments throughout the semester. I describe each assignment below, with more detail provided on our [assignments page](https://econ771s24.classes.ianmccarthyecon.com/assignments). 

### Research Proposals

You will submit four research proposals throughout the semester. These are short, 1-2 page documents that outline a problem/motivation, a related research question, potential data to help answer this question, and a proposed empirical strategy. The goal of these proposals is to help you develop your own research ideas and to get feedback from me and your classmates. You will submit one proposal roughly every 3 weeks and present the proposal to the class. After you've presented and received feedback on four proposals, you will develop the best of these proposals into a more complete research plan. Details of the research proposal and plans are available on the [assignments page](https://econ771s24.classes.ianmccarthyecon.com/assignments) of our class website.

Please select a date to present your research proposals on the **Proposals** tab of the Google Sheet [here](https://docs.google.com/spreadsheets/d/19LovendEZg3Qk_5Wgy-we_9owO8sPnseU5blbik86MI/edit?usp=sharing) no later than **Friday, January 26**. Note that even though the presentations are spread out over three weeks for each proposal, everyone has the same due date.

### Presentations

You will present four papers throughout the course of the semester. Please note your selected papers and class dates on the **Presentations** tab of the Google Sheet [here](https://docs.google.com/spreadsheets/d/19LovendEZg3Qk_5Wgy-we_9owO8sPnseU5blbik86MI/edit?usp=sharing) no later than **Friday, January 26**. If you do not select papers by then, I will assign you papers randomly. The list of potential papers to present and details of the expectations for each presentation are available on the [assignments page](https://econ771s24.classes.ianmccarthyecon.com/assignments) of our class website.

### Empirical Exercises

There is an applied component of this course where we spend some time with a real-life causal inference question. These will require some of your time outside of class to get the data in working order and implement the relevant identification strategy and econometric estimator. Raw data for each exercise will be provided on our class OneDrive notebook, the link to which is on **Canvas**. There are four possible empirical exercises, from which you must choose one. Please note your selection paper on the **Exercises** tab of the Google Sheet [here](https://docs.google.com/spreadsheets/d/19LovendEZg3Qk_5Wgy-we_9owO8sPnseU5blbik86MI/edit?usp=sharing) no later than **February 2**. 


### Important Deadlines

This section is just to highlight important dates for assignments throughout the semester. Note that late assignments will receive an automatic 5% reduction in the grade for each day the assignment is turned in after the due date.

   - **Select Papers to Present** no later than **January 26**: Note the papers you plan to present on the **Presentations** tab of the Google Sheet [here](https://docs.google.com/spreadsheets/d/19LovendEZg3Qk_5Wgy-we_9owO8sPnseU5blbik86MI/edit?usp=sharing). Only one student per paper, so this is first-come first-served. Remember you need to select four papers to present throughout the semester. Please spread these presentations out over the semester.
   - **Select Research Proposal Presentation Dates** no later than **January 26**: Note the dates you plan to present your proposals on the **Proposals** tab of the Google Sheet [here](https://docs.google.com/spreadsheets/d/19LovendEZg3Qk_5Wgy-we_9owO8sPnseU5blbik86MI/edit?usp=sharing). Only two students can present on any given Friday.
   - **Select Empirical Exercise** no later than **February 2**: Note your selection on the **Exercises** tab of the Google Sheet [here](https://docs.google.com/spreadsheets/d/19LovendEZg3Qk_5Wgy-we_9owO8sPnseU5blbik86MI/edit?usp=sharing). No more than two students per exercise.
   - The first round of **Research Proposals and Presentations** is due by class time on **February 2**
   - The second round of **Research Proposals and Presentations** is due by class time on **February 23**
   - The third round of **Research Proposals and Presentations** is due by class time on **March 22**
   - The fourth and final round of **Research Proposals and Presentations** is due by class time on **April 12**
   - **Empirical Exercises** are due on **April 26**
   - **Final Research Plans** are due on **April 29**


## Final grades

   - **50%** for research proposals (10% for each proposal and 10% for the research plan)
   - **30%** for empirical exercises
   - **20%** for presentations of selected papers (5% each)

Letter grades will be assigned at the end of the course based on total score achieved:
(A = 100-93%, A- = 92.99-90%, B+ = 89.99-87%, B = 86.99-83%, B- = 82.99-80%, C+ = 79.99-77%, C = 76.99-73%, C- = 72.99-70%, D+ = 69.99-67%, D = 66.99-60%, F = 60% or less)

