---
title: "Health Insurance and Healthcare"
---

The goal for today's class is to understand the demand for healthcare and health insurance, as well as the complexities of health insurance choice. Focus areas and selected papers for this class are listed below. 

### Demand for Healthcare and Health Insurance: The RAND and Oregon Experiments
The RAND Health Insurance Experiment (HIE) was conducted between 1974 and 1982 and was one of the largest and most comprehensive studies of its time, randomly assigning families to different health insurance plans with varying levels of cost-sharing to assess the impact on healthcare utilization and outcomes. In a more recent experiment, a limited number of Medicaid slots were allocated through a lottery to low-income adults in Oregon. This lottery system essentially created a randomized controlled experiment, allowing the researchers to compare outcomes between those who received Medicaid coverage and those who did not. We'll discuss the RAND HI via @aron-dine2013, and we'll discuss the Oregon Medicaid experiment with @finkelstein2012. 

### Complexities of Health Insurance Choice
There are many papers examining the presence and effects of poor decision making in health insurance choice. As examples of these papers, we'll discuss @abaluck2011, @ketcham2012, @ketcham2016 and @abaluck2016. The authors show that many people make suboptimal choices when selecting health insurance plans, and the papers essentially debate the source of this "poor" decision making and the scope of improvment from government intervention. These papers collectively speak to the importance of understanding how people make decisions in health insurance markets, and the implications for designing policies that can improve outcomes and best match people to health insurance plans.

### Improving Health Insurance Choice
Building off the literature documenting poor health insurance choices, the natural policy question is whether we can improve health insurance choices at relatively low cost. This is a difficult question to answer, as it requires a clear understanding of why people make poor choices. We'll discuss @brot-goldberg2023 as an example of research in this area.

This paper leverages two natural experiments to study the impact of default options in public drug insurance for low-income elderly in the U.S. The study finds that default plan selections significantly influence plan enrollment and drug utilization, with 96% of beneficiaries following an exogenously changed default. The paper proposes a general framework for choice under costly cognition, suggesting that both paternalistic defaults (steering consumers to suitable plans) and 'shocking' defaults (triggering active choices) could be optimal, depending on a key parameter: the elasticity of active choice propensity relative to the default value. However, they find this elasticity to be close to zero, indicating minimal active choice difference between beneficiaries assigned to well-matched vs. poorly-matched defaults. The study also shows that poorly-matched defaults lead to significant declines in drug consumption, suggesting that the welfare losses from following these defaults likely outweigh any potential gains from induced active choices. A third natural experiment reveals that the limited active choice observed seems largely random, driven by transient attentional shifts within beneficiaries. The results highlight the importance of paternalistic defaults in insurance market design, likely benefiting beneficiaries more than harming them.