---
title: "Effects of Health Insurance"
---

The goal of today's class is to study the effects of health insurance. In this general area, one topic that has been very well studied but that we won't discuss is the role of moral hazard in health insurance. For more details on that, see @einav2018. Moral hazard is central to the design and evaluation of health insurance policies, but we just don't have enough time to talk about everything! Focus areas and selected papers for this class are listed below.

### Financial Effects of Health Insurance
In reducing the financial burden of healthcare costs, health insurance should relax a household's budget constraint and reduce the probability of default on other financial obligations. This is an important consideration for policymakers, as it speaks to the broader economic impacts of health insurance. As an example of this area of research, we'll discuss @hu2018. This paper examines the financial impacts of the Medicaid expansions under the Affordable Care Act (ACA). The authors use credit report data and a difference-in-differences strategy to analyze the financial outcomes for individuals in states that expanded Medicaid compared to those in states that did not. They find that ACA Medicaid expansions led to significant reductions in the amount of unpaid bills, the amount of debt in collections, and the credit scores of individuals who gained Medicaid coverage. The reductions in unpaid bills and debts were primarily driven by decreases in medical debts, but not exclusively.

### Health Effects of Health Insurance
While it seems obvious to some, it's not immediately clear that health insurance should improve health. We'll discuss two papers that show strong evidence that health insurance does improve health. The first is @miller2021, which relates to Medicaid expansion. The second is @goldin2021, which examines health insurance and mortality among non-Medicaid eligible adults. These are more recent papers, but that's because only recently did we begin to get the proper data to answer this question definitively.

### Health Insurance and Overall Welfare
While health insurance clearly has direct effects on patients, it also has indirect effects on other parties, such as providers, employers, and taxpayers. These indirect effects are important to consider when evaluating the overall welfare effects of health insurance. @finkelstein2007 and @finkelstein2019jpe are excellent examples of papers in this area.

I lump these papers together because they both speak to effects of health insurance beyond an individual patient or enrollee. @finkelstein2007 examines the broader economic impacts of the introduction of Medicare in the U.S. She finds that the introduction of Medicare led to a significant increase in hospital spending, responsible for a substantial portion of the 37 percent increase in hospital spending between 1965 and 1970. They also discuss how the increased spending due to Medicare led to rapid growth in the healthcare sector, influencing not only healthcare delivery but also labor markets and infrastructure within the sector. The paper underscores the need to consider both direct and indirect effects of large scale policies such as Medicare.

@finkelstein2019jpe considers the value of Medicaid coverage using the Oregon Health Insurance Experiment. The study estimates that low-income uninsured adults' willingness to pay for Medicaid ranges from $0.5 to $1.2 per dollar of the resource cost of providing Medicaid. The authors show that 60% of Medicaid's gross expenditures, or $3600 per recipient, are essentially transfers to parties who would otherwise subsidize medical care for the low-income uninsured, leaving the net cost of Medicaid at about $1450 per recipient. The paper concludes that Medicaid serves dual roles: as a monetary transfer to external parties and as a subsidized insurance product for recipients, with recipient willingness to pay for Medicaid significantly below its gross cost​.


