---
title: "Information and Choice"
---

The goal for today's class is to understand the effects of information disclosure on insurance and provider choice. On the insurance side, prices (as in premiums, deductibles, etc.) are typically readily available, so the literature on that area tends to focus on quality disclosure. On the provider side, there is a literature focusing on both quality and price transparency, which we'll discuss separately. Focus areas and selected papers for this class are listed below.

### Information and Insurance Choice
We'll start our discussion with @chernew2008, who presents a nice model of patient learning in the context of quality disclosure. We'll also discuss @dafny2008, which is one of the seminal papers in this area. The authors compare plan choices before and after the release of plan quality information, and they essentially ask whether the disclosure of such information is really "new" or if the market had already learned about plan quality through other means.

### Quality Information and Provider Choice
Since healthcare is an experience good, we simply don't know the quality of our care until after we've received it. But we might still be able to better predict quality based on providers' past outcomes. Such information has historically been difficult or impossible to observe, but this is changing. We'll discuss two studies on the effects of quality disclosure on provider choice: @dranove2003 and @brown2023.

### Price Information and Provider Choice
In the U.S., prices for healthcare services are notoriously difficult to observe, but there have been recent efforts to change this. We'll discuss two studies on the effects of price disclosure on provider choice: @christensen2020 and @brown2019.


