---
title: "Background on Physician Learning"
---

Module 5 covers physician learning. This is an important yet complex aspect of health economics, encompassing how doctors acquire and update their medical knowledge and skills over time. For our purposes, we'll think of learning outside of the formal education process (e.g., learning by experience, from peers, or impediments to learning due to other external factors). For today, I'll focus on @ching2013 as an introduction to the topic. This paper discusses on the evolution of learning models in consumer and physician behavior over the past two decades. It reviews the literature on learning models, particularly emphasizing model in @erdem1996. The authors discuss how learning models have significantly enhanced understanding of consumer behavior, especially in the context of brand loyalty and the long-term effects of advertising. The paper also highlights the challenges in learning models, such as differentiating learning as a dynamic source from other factors like habit persistence and inventories, and improving the identification of learning models through direct measures of signals, perceptions, and expectations​.