---
title: "Myopic Learning"
---

The bulk of the early literature on physician learning considers the case of a physician who is myopic, in the sense that they do not consider the impact of their actions on future patients. We'll focus on the following areas and papers:

### Learning with Spillovers
In the context of prescription drugs, the simplest learning model considers a single agent learning about the best drug based on their experience with that drug. But in a prescription drug setting, physicians can learn about drugs based on their experience with other patients. We'll discuss @coscelli2004 as an example of this work. In that paper, the authors incorporate a more comprehensive learning model that allows for spillovers across all patients of a given doctor, as well as heterogeneity in patient informativeness. This approach is particularly relevant for pharmaceutical markets, where prescription drugs are often used for multiple diagnoses. The paper extends existing literature by using micro-data to quantify network-type spillovers across patients belonging to the same doctor, a significant contribution to the literature on physician learning. This model helps in understanding how doctors update their beliefs and make prescribing decisions based on the experiences of their patients with new medications, providing valuable insights into the dynamics of new drug entry in the market​

### Learning from Others
While most models consider learning based on the individual's own experience, physicians also learn from many other sources. We'll discuss @chandra2007 and @agha2018 as examples of such learning, the first of which examines learning from peers and the second considers learning from new research trials.