---
title: "Variation and Physician Agency: What we're learning"
---

The goal for today's class is to further understand the current literature on physician agency.

### @beckert2018 and xxx
These papers collectively study the role of PCPs in patient healthcare choices, hilighting the potential role for physician agency in healthcare decisions.

### @walden2016
This is an older working paper that likely isn't going to be published. But I think it's important nonetheless, as it deals with the potential for physician agency in primary care physician referral decisions.

### @ho2014
This paper examines the role of physician agency in the context of capitated payments (e.g., how physicians are paid rather than exactly how much they are paid). 

### @gaynor2016
This paper studies the role of physicians in hospital choice, focusing on plausibly exogenous changes to the set of hospitals from which a physician could select. The paper is also a great example of recent work on consideration sets in discrete choice analysis.

