---
title: "Health Insurance: What we're learning"
---

The more recent literature in health insurance tends to consider more indirect effects of health insurance, such as reductions in payment delinquency in other areas (non-healthcare spending) or effects of health insurance on provider behaviors. There is also a recent literature concerned with how to improve the quality of an enrollee's health insurance plan, which draws heavily on earlier studies of health insurance demand but focuses on more current policy issues such as administrative barriers, default plan selections, etc. For this class, we'll focus on the following papers:

### @hu2018
This paper examines the financial impacts of the Medicaid expansions under the Affordable Care Act (ACA). The authors use credit report data and a difference-in-differences strategy to analyze the financial outcomes for individuals in states that expanded Medicaid compared to those in states that did not. They find that ACA Medicaid expansions led to significant reductions in the amount of unpaid bills, the amount of debt in collections, and the credit scores of individuals who gained Medicaid coverage. The reductions in unpaid bills and debts were primarily driven by decreases in medical debts, but not exclusively.

### @finkelstein2007 and @finkelstein2019jpe
I lump these papers together because they both speak to effects of health insurance beyond an individual patient or enrollee. @finkelstein2007 examines the broader economic impacts of the introduction of Medicare in the U.S. She finds that the introduction of Medicare led to a significant increase in hospital spending, responsible for a substantial portion of the 37 percent increase in hospital spending between 1965 and 1970. They also discuss how the increased spending due to Medicare led to rapid growth in the healthcare sector, influencing not only healthcare delivery but also labor markets and infrastructure within the sector. The paper underscores the need to consider both direct and indirect effects of large scale policies such as Medicare.

@finkelstein2019jpe considers the value of Medicaid coverage using the Oregon Health Insurance Experiment. The study estimates that low-income uninsured adults' willingness to pay for Medicaid ranges from $0.5 to $1.2 per dollar of the resource cost of providing Medicaid. The authors show that 60% of Medicaid's gross expenditures, or $3600 per recipient, are essentially transfers to parties who would otherwise subsidize medical care for the low-income uninsured, leaving the net cost of Medicaid at about $1450 per recipient. The paper concludes that Medicaid serves dual roles: as a monetary transfer to external parties and as a subsidized insurance product for recipients, with recipient willingness to pay for Medicaid significantly below its gross cost​.

### @brot-goldberg2023
This paper leverages two natural experiments to study the impact of default options in public drug insurance for low-income elderly in the U.S. The study finds that default plan selections significantly influence plan enrollment and drug utilization, with 96% of beneficiaries following an exogenously changed default. The paper proposes a general framework for choice under costly cognition, suggesting that both paternalistic defaults (steering consumers to suitable plans) and 'shocking' defaults (triggering active choices) could be optimal, depending on a key parameter: the elasticity of active choice propensity relative to the default value. However, they find this elasticity to be close to zero, indicating minimal active choice difference between beneficiaries assigned to well-matched vs. poorly-matched defaults. The study also shows that poorly-matched defaults lead to significant declines in drug consumption, suggesting that the welfare losses from following these defaults likely outweigh any potential gains from induced active choices. A third natural experiment reveals that the limited active choice observed seems largely random, driven by transient attentional shifts within beneficiaries. The results highlight the importance of paternalistic defaults in insurance market design, likely benefiting beneficiaries more than harming them.