---
title: "Participation"
---

Participation is graded based on your engagement in small-group homework discussions. A large portion of this class is about learning how to work with **real world** data. To do this, we will spend significant in-class time reviewing the assignments and updating our work based on collective feedback. For each assignment, students will be placed into small groups to discuss each others' work. Your participation grade will derive from a peer evaluation based on these small group sessions. 

At the end of each assignment, each member of each group will be asked to rate the feedback of their peers on a scale of 1-3. A value of 1 reflects insufficient effort or engagement, a value of 2 reflects sufficient effort, and a value of 3 reflects excellent effort. I anticipate small groups of at least 4 students, which means you will receive peer scores from at least 3 other students for each assignment. Your median score across all peer evaluations will be used as your participation grade in that assignment. For example, if you receive peer scores of 3, 3, and 1, your participation score would be 3. If the median value is a tie, your participation grade will be the highest of the possible values. 

At the end of the semester, your peer participation grades from each assignment will be totaled. Your final participation grade will be based on your total number of participation points out of 10. Note there are 15 possible participation points, so there is some margin for error here if you happen to miss class during a small group session or simply aren't engaged in one of the review sessions for some reason.
